---
# file: manage.yml
# Primary file for running ansible

- hosts: Servers
  roles:
          - ssh

# anything that needs sudo
- hosts: Servers
  become: yes
  become_method: sudo
  remote_user: ubuntu
  roles:
          - update

